"""codelens v2 baseline

Revision ID: 0001_codelens_v2
Revises:
Create Date: 2026-08-09 22:41:51.899372
"""

from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa
from alembic import op

revision: str = "0001_codelens_v2"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artifacts",
        sa.Column("reference", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("storage_key", sa.String(length=128), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("reference"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_index(op.f("ix_artifacts_run_id"), "artifacts", ["run_id"], unique=False)
    op.create_table(
        "recent_repositories",
        sa.Column("repository_path", sa.Text(), nullable=False),
        sa.Column("last_reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("repository_path"),
    )
    op.create_index(
        op.f("ix_recent_repositories_last_reviewed_at"),
        "recent_repositories",
        ["last_reviewed_at"],
        unique=False,
    )
    op.create_table(
        "recent_repository_settings",
        sa.Column("settings_id", sa.Integer(), nullable=False),
        sa.Column("recent_repository_limit", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "recent_repository_limit BETWEEN 1 AND 20", name="ck_recent_repository_settings_limit"
        ),
        sa.PrimaryKeyConstraint("settings_id"),
    )
    op.bulk_insert(
        sa.table(
            "recent_repository_settings",
            sa.column("settings_id", sa.Integer()),
            sa.column("recent_repository_limit", sa.Integer()),
        ),
        [{"settings_id": 1, "recent_repository_limit": 10}],
    )
    op.create_table(
        "review_profiles",
        sa.Column("profile_id", sa.String(length=128), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("reviewer_selection_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("revision >= 1", name="ck_review_profiles_positive_revision"),
        sa.PrimaryKeyConstraint("profile_id"),
    )
    op.create_index(
        "uq_review_profiles_single_default",
        "review_profiles",
        ["is_default"],
        unique=True,
        sqlite_where=sa.text("is_default IS 1"),
    )
    now = datetime.now(UTC)
    op.bulk_insert(
        sa.table(
            "review_profiles",
            sa.column("profile_id", sa.String(length=128)),
            sa.column("revision", sa.Integer()),
            sa.column("name", sa.String(length=120)),
            sa.column("is_default", sa.Boolean()),
            sa.column("reviewer_selection_json", sa.Text()),
            sa.column("created_at", sa.DateTime(timezone=True)),
            sa.column("updated_at", sa.DateTime(timezone=True)),
        ),
        [
            {
                "profile_id": "profile-balanced",
                "revision": 1,
                "name": "Balanced Review",
                "is_default": True,
                "reviewer_selection_json": '{"mode":"adaptive"}',
                "created_at": now,
                "updated_at": now,
            }
        ],
    )
    op.create_table(
        "review_tasks",
        sa.Column("task_id", sa.String(length=128), nullable=False),
        sa.Column("repository_id", sa.String(length=128), nullable=False),
        sa.Column("repository_path", sa.Text(), nullable=True),
        sa.Column("repository_realpath_hash", sa.String(length=64), nullable=False),
        sa.Column("git_common_dir_hash", sa.String(length=64), nullable=False),
        sa.Column("scope_json", sa.Text(), nullable=False),
        sa.Column("base_oid", sa.String(length=64), nullable=False),
        sa.Column("head_oid", sa.String(length=64), nullable=False),
        sa.Column("overlay_hash", sa.String(length=64), nullable=True),
        sa.Column("overlay_artifact_ref", sa.String(length=128), nullable=True),
        sa.Column("candidate_paths_json", sa.Text(), nullable=False),
        sa.Column("file_exclusion_policy_json", sa.Text(), nullable=False),
        sa.Column("file_exclusion_policy_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("selected_agent_versions_json", sa.Text(), nullable=False),
        sa.Column("selection_request_json", sa.Text(), nullable=False),
        sa.Column("profile_source_id", sa.String(length=128), nullable=True),
        sa.Column("profile_source_revision", sa.Integer(), nullable=True),
        sa.Column("trigger_source", sa.String(length=16), nullable=True),
        sa.Column("supersede_policy", sa.String(length=32), nullable=True),
        sa.Column("idempotency_key", sa.String(length=64), nullable=True),
        sa.Column("trigger_slot_key", sa.String(length=64), nullable=True),
        sa.Column("planning_context_json", sa.Text(), nullable=True),
        sa.Column("planning_context_hash", sa.String(length=64), nullable=True),
        sa.Column("has_partial_coverage", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("prompt_locale", sa.String(length=8), nullable=False),
        sa.Column("external_context_json", sa.Text(), nullable=True),
        sa.Column(
            "existing_findings_json", sa.Text(), server_default="[]", nullable=False
        ),
        sa.Column(
            "existing_findings_hash",
            sa.String(length=64),
            server_default="4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e4d8e80efc93a6c2e61e7e7",
            nullable=False,
        ),
        sa.Column("worktree_id", sa.String(length=128), nullable=True),
        sa.Column("snapshot_id", sa.String(length=128), nullable=True),
        sa.Column("cancellation_requested", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("task_id"),
    )
    op.create_index(
        op.f("ix_review_tasks_git_common_dir_hash"),
        "review_tasks",
        ["git_common_dir_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_review_tasks_repository_id"), "review_tasks", ["repository_id"], unique=False
    )
    op.create_index(
        "ix_review_tasks_trigger_slot",
        "review_tasks",
        ["trigger_slot_key", "status", "created_at"],
        unique=False,
        sqlite_where=sa.text("trigger_slot_key IS NOT NULL"),
    )
    op.create_index(
        "uq_review_tasks_idempotency_key",
        "review_tasks",
        ["idempotency_key"],
        unique=True,
        sqlite_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.create_table(
        "review_file_scopes",
        sa.Column("task_id", sa.String(length=128), nullable=False),
        sa.Column("scope_json", sa.Text(), nullable=False),
        sa.Column("scope_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["review_tasks.task_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("task_id"),
    )
    op.create_table(
        "agent_execution_specs",
        sa.Column("task_id", sa.String(length=128), nullable=False),
        sa.Column("logical_node_id", sa.String(length=128), nullable=False),
        sa.Column("spec_json", sa.Text(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("prompt_artifact_ref", sa.String(length=128), nullable=False),
        sa.Column("prompt_artifact_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["prompt_artifact_ref"],
            ["artifacts.reference"],
        ),
        sa.ForeignKeyConstraint(["task_id"], ["review_tasks.task_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("task_id", "logical_node_id"),
    )
    op.create_table(
        "dag_checkpoints",
        sa.Column("task_id", sa.String(length=128), nullable=False),
        sa.Column("node_key", sa.String(length=256), nullable=False),
        sa.Column("logical_attempt_group", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("execution_attempts", sa.Integer(), nullable=False),
        sa.Column("validation_attempts", sa.Integer(), nullable=False),
        sa.Column("artifact_ref", sa.String(length=128), nullable=True),
        sa.Column("artifact_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "review_completion_status",
            sa.String(length=32),
            server_default="complete",
            nullable=False,
        ),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("run_id", sa.String(length=128), nullable=True),
        sa.Column("node_role", sa.String(length=32), nullable=True),
        sa.Column("agent_version", sa.String(length=128), nullable=True),
        sa.Column("pass_index", sa.Integer(), nullable=True),
        sa.Column("shard_id", sa.String(length=128), nullable=True),
        sa.Column("capability_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("result_summary_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["review_tasks.task_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("task_id", "node_key"),
    )
    op.create_index(
        "uq_dag_checkpoints_run_id",
        "dag_checkpoints",
        ["run_id"],
        unique=True,
        sqlite_where=sa.text("run_id IS NOT NULL"),
    )
    op.create_table(
        "events",
        sa.Column("event_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["review_tasks.task_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(op.f("ix_events_task_id"), "events", ["task_id"], unique=False)
    op.create_table(
        "finding_clusters",
        sa.Column("cluster_id", sa.String(length=128), nullable=False),
        sa.Column("task_id", sa.String(length=128), nullable=False),
        sa.Column("snapshot_id", sa.String(length=128), nullable=False),
        sa.Column("cluster_key", sa.String(length=256), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["review_tasks.task_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("cluster_id"),
        sa.UniqueConstraint("task_id", "cluster_key", name="uq_finding_clusters_task_key"),
    )
    op.create_index(
        op.f("ix_finding_clusters_task_id"), "finding_clusters", ["task_id"], unique=False
    )
    op.create_table(
        "jobs",
        sa.Column("task_id", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["review_tasks.task_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("task_id"),
    )
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_table(
        "review_plans",
        sa.Column("task_id", sa.String(length=128), nullable=False),
        sa.Column("plan_json", sa.Text(), nullable=False),
        sa.Column("plan_hash", sa.String(length=64), nullable=False),
        sa.Column("catalog_version", sa.String(length=128), nullable=False),
        sa.Column("capability_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["review_tasks.task_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("task_id"),
    )
    op.create_table(
        "task_worktrees",
        sa.Column("worktree_id", sa.String(length=128), nullable=False),
        sa.Column("task_id", sa.String(length=128), nullable=False),
        sa.Column("owned_path_hash", sa.String(length=64), nullable=False),
        sa.Column("common_dir_hash", sa.String(length=64), nullable=False),
        sa.Column("head_oid", sa.String(length=64), nullable=False),
        sa.Column("ownership_token_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["review_tasks.task_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("worktree_id"),
        sa.UniqueConstraint("task_id"),
    )
    op.create_index(
        op.f("ix_task_worktrees_common_dir_hash"),
        "task_worktrees",
        ["common_dir_hash"],
        unique=False,
    )
    op.create_table(
        "verdict_decisions",
        sa.Column("verdict_decision_id", sa.String(length=128), nullable=False),
        sa.Column("task_id", sa.String(length=128), nullable=False),
        sa.Column("verifier_run_id", sa.String(length=128), nullable=True),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["review_tasks.task_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("verdict_decision_id"),
    )
    op.create_index(
        op.f("ix_verdict_decisions_task_id"),
        "verdict_decisions",
        ["task_id"],
        unique=False,
    )
    op.create_table(
        "verdict_decision_clusters",
        sa.Column("verdict_decision_id", sa.String(length=128), nullable=False),
        sa.Column("cluster_id", sa.String(length=128), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cluster_id"], ["finding_clusters.cluster_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["verdict_decision_id"],
            ["verdict_decisions.verdict_decision_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("verdict_decision_id", "cluster_id"),
        sa.UniqueConstraint("cluster_id", name="uq_verdict_decision_cluster"),
        sa.UniqueConstraint(
            "verdict_decision_id",
            "ordinal",
            name="uq_verdict_decision_cluster_ordinal",
        ),
    )
    op.create_table(
        "findings",
        sa.Column("finding_id", sa.String(length=128), nullable=False),
        sa.Column("task_id", sa.String(length=128), nullable=False),
        sa.Column("node_key", sa.String(length=256), nullable=False),
        sa.Column("fingerprint", sa.String(length=256), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("verdict_decision_id", sa.String(length=128), nullable=False),
        sa.Column("verification_status", sa.String(length=32), nullable=True),
        sa.Column("path", sa.String(length=1024), nullable=False),
        sa.Column("start_line", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["review_tasks.task_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["verdict_decision_id"],
            ["verdict_decisions.verdict_decision_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("finding_id"),
        sa.UniqueConstraint("task_id", "fingerprint", name="uq_findings_task_fingerprint"),
    )
    op.create_index(op.f("ix_findings_task_id"), "findings", ["task_id"], unique=False)
    op.create_table(
        "agent_execution_skill_artifacts",
        sa.Column("task_id", sa.String(length=128), nullable=False),
        sa.Column("logical_node_id", sa.String(length=128), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("artifact_ref", sa.String(length=128), nullable=False),
        sa.Column("artifact_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["artifact_ref"],
            ["artifacts.reference"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id", "logical_node_id"],
            ["agent_execution_specs.task_id", "agent_execution_specs.logical_node_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("task_id", "logical_node_id", "ordinal"),
    )
    op.create_table(
        "candidate_findings",
        sa.Column("candidate_id", sa.String(length=128), nullable=False),
        sa.Column("task_id", sa.String(length=128), nullable=False),
        sa.Column("node_key", sa.String(length=256), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("snapshot_id", sa.String(length=128), nullable=False),
        sa.Column("reviewer_reference", sa.String(length=128), nullable=False),
        sa.Column("fingerprint", sa.String(length=256), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id", "node_key"],
            ["dag_checkpoints.task_id", "dag_checkpoints.node_key"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["task_id"], ["review_tasks.task_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("candidate_id"),
    )
    op.create_index(
        op.f("ix_candidate_findings_run_id"), "candidate_findings", ["run_id"], unique=False
    )
    op.create_index(
        op.f("ix_candidate_findings_task_id"), "candidate_findings", ["task_id"], unique=False
    )
    op.create_table(
        "finding_cluster_candidates",
        sa.Column("cluster_id", sa.String(length=128), nullable=False),
        sa.Column("candidate_id", sa.String(length=128), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"], ["candidate_findings.candidate_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["cluster_id"], ["finding_clusters.cluster_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("cluster_id", "candidate_id"),
        sa.UniqueConstraint("candidate_id", name="uq_cluster_candidate_membership"),
        sa.UniqueConstraint("cluster_id", "ordinal", name="uq_cluster_candidate_ordinal"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("finding_cluster_candidates")
    op.drop_index(op.f("ix_candidate_findings_task_id"), table_name="candidate_findings")
    op.drop_index(op.f("ix_candidate_findings_run_id"), table_name="candidate_findings")
    op.drop_table("candidate_findings")
    op.drop_table("agent_execution_skill_artifacts")
    op.drop_index(op.f("ix_findings_task_id"), table_name="findings")
    op.drop_table("findings")
    op.drop_table("verdict_decision_clusters")
    op.drop_index(op.f("ix_task_worktrees_common_dir_hash"), table_name="task_worktrees")
    op.drop_table("task_worktrees")
    op.drop_table("review_plans")
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_verdict_decisions_task_id"), table_name="verdict_decisions")
    op.drop_table("verdict_decisions")
    op.drop_index(op.f("ix_finding_clusters_task_id"), table_name="finding_clusters")
    op.drop_table("finding_clusters")
    op.drop_index(op.f("ix_events_task_id"), table_name="events")
    op.drop_table("events")
    op.drop_table("review_file_scopes")
    op.drop_index(
        "uq_dag_checkpoints_run_id",
        table_name="dag_checkpoints",
        sqlite_where=sa.text("run_id IS NOT NULL"),
    )
    op.drop_table("dag_checkpoints")
    op.drop_table("agent_execution_specs")
    op.drop_index(
        "uq_review_tasks_idempotency_key",
        table_name="review_tasks",
        sqlite_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.drop_index(
        "ix_review_tasks_trigger_slot",
        table_name="review_tasks",
        sqlite_where=sa.text("trigger_slot_key IS NOT NULL"),
    )
    op.drop_index(op.f("ix_review_tasks_repository_id"), table_name="review_tasks")
    op.drop_index(op.f("ix_review_tasks_git_common_dir_hash"), table_name="review_tasks")
    op.drop_table("review_tasks")
    op.drop_index(
        "uq_review_profiles_single_default",
        table_name="review_profiles",
        sqlite_where=sa.text("is_default IS 1"),
    )
    op.drop_table("review_profiles")
    op.drop_table("recent_repository_settings")
    op.drop_index(op.f("ix_recent_repositories_last_reviewed_at"), table_name="recent_repositories")
    op.drop_table("recent_repositories")
    op.drop_index(op.f("ix_artifacts_run_id"), table_name="artifacts")
    op.drop_table("artifacts")
    # ### end Alembic commands ###
